export enum GameState {
    NOT_STARTED,
    STARTING,
    WAIT,
    ASKING_QUESTION_QCM,
    ASKING_QUESTION_QRL,
    WAITING_FOR_ANSWERS,
    SHOW_RESULTS,
    LAST_QUESTION,
    SHOW_FINAL_RESULTS,
}
